### ISSUE TITLE
Option to include / exclude specific camera's

### ISSUE THREAD

**Issue by extera-nl** [OldTyT/frigate-telegram#11]
First of all: Thank you! Your repo is excellent! Works like a charm!

For some of my camera's detection in frigate is enabled because I want to use double take for facial recognition. 
I would like to have the option to exclude these camera's from the notifications, because now I get a lot of notifications.

Something like 

FRIGATE_INCLUDE_CAMERA: [cam 1, cam 2]  # Default: All
FRIGATE_EXCLUDE_CAMERA: [cam 1, cam 2]  # Default: None

Please let me know if I can help testing this out!

**Comment by OldTyT** [comment]
Hi! Thanks!

Please check the correctness of the work

**Comment by OldTyT** [comment]
@extera-nl ^^^

**Comment by extera-nl** [comment]
Works as expected! Very nice!

**Comment by OldTyT** [comment]
> Works as expected! Very nice!

Thanks! Please give a star to the repository)
