### ISSUE TITLE
Error response from daemon: manifest unknown

### ISSUE THREAD

**Issue by Dionisgr** [OldTyT/frigate-telegram#18]
$ sudo docker compose up 
[+] Running 2/2
 ✘ frigate-telegram Error manifest unknown                                 1.9s 
 ✘ redis Error            context canceled                                 1.9s 
Error response from daemon: manifest unknown

**Comment by OldTyT** [comment]
@Dionisgr, hi!
Thanks for using my code.
I fixed it.
