### ISSUE TITLE
[feature] Sub-Label

### ISSUE THREAD

**Issue by Knockback2003** [OldTyT/frigate-telegram#19]
As I saw from your code, you already receive the sublabel via frigate and extract it from the Json payload. Unfortunately it is missing in the `SendMessageEvent` function. I use deepstack and the sublabel gives me the name of the person recognized, which would be nice to see in the Telegram message

**Comment by OldTyT** [comment]
@Knockback2003. hi!
Thanks for using my code.
Send me please your events json.
https://docs.frigate.video/integrations/api/#events

**Comment by Knockback2003** [comment]
Thank's for the fast reply, here my events json example:

```
{
  "before": {
    "id": "1731058905.394719-j3lkiy",
    "camera": "one",
    "frame_time": 1731058905.394719,
    "snapshot": null,
    "label": "person",
    "sub_label": null,
    "top_score": 0,
    "false_positive": true,
    "start_time": 1731058905.394719,
    "end_time": null,
    "score": 0.71484375,
    "box": [
      1789,
      3,
      2043,
      755
    ],
    "area": 191008,
    "ratio": 0.3377659574468085,
    "region": [
      1784,
      0,
      2560,
      776
    ],
    "stationary": false,
    "motionless_count": 0,
    "position_changes": 0,
    "current_zones": [],
    "entered_zones": [],
    "has_clip": false,
    "has_snapshot": false,
    "attributes": {},
    "current_attributes": []
  },
  "after": {
    "id": "1731058905.394719-j3lkiy",
    "camera": "one",
    "frame_time": 1731058905.429196,
    "snapshot": {
      "frame_time": 1731058905.429196,
      "box": [
        1734,
        5,
        2041,
        847
      ],
      "area": 258494,
      "region": [
        1438,
        0,
        2374,
        936
      ],
      "score": 0.609375,
      "attributes": []
    },
    "label": "person",
    "sub_label": null,
    "top_score": 0.71484375,
    "false_positive": false,
    "start_time": 1731058905.394719,
    "end_time": null,
    "score": 0.609375,
    "box": [
      1734,
      5,
      2041,
      847
    ],
    "area": 258494,
    "ratio": 0.3646080760095012,
    "region": [
      1438,
      0,
      2374,
      936
    ],
    "stationary": false,
    "motionless_count": 0,
    "position_changes": 1,
    "current_zones": [],
    "entered_zones": [],
    "has_clip": true,
    "has_snapshot": true,
    "attributes": {},
    "current_attributes": []
  },
  "type": "new"
  "after": {
    "id": "1731058905.394719-j3lkiy",
    "camera": "one",
    "frame_time": 1731058906.358459,
    "snapshot": {
      "frame_time": 1731058905.932816,
      "box": [
        1714,
        8,
        2062,
        833
      ],
      "area": 287100,
      "region": [
        1375,
        0,
        2391,
        1016
      ],
      "score": 0.5234375,
      "attributes": []
    },
    "label": "person",
    "sub_label": null,
    "top_score": 0.71484375,
    "false_positive": false,
    "start_time": 1731058905.394719,
    "end_time": 1731058906.701762,
    "score": 0.546875,
    "box": [
      1716,
      3,
      2029,
      795
    ],
    "area": 247896,
    "ratio": 0.3952020202020202,
    "region": [
      1260,
      0,
      2412,
      1152
    ],
    "stationary": false,
    "motionless_count": 10,
    "position_changes": 1,
    "current_zones": [],
    "entered_zones": [],
    "has_clip": true,
    "has_snapshot": true,
    "attributes": {},
    "current_attributes": []
  },
  "type": "end"
}
```

**Comment by OldTyT** [comment]
@Knockback2003, Hello! There is no person name in your JSON. Where can I get it?

**Comment by OldTyT** [comment]
I can add a `sub_label` to the text of a telegram message, but does it make sense?

**Comment by Knockback2003** [comment]
Yes this makes sense. The sublabel is by Default null and is set by deepstack or other local face recognition ai. Deepstack provides the name when the confidence is `80 percent` or higher. In this case the persons face was not cleary for deepstack so the sub label was `null`. You can make a simple If function like `if [...] != null` and then add via `+=` the sublabel part to the telegram notification. I would open a pull request but I mess always up with Python haha.

**Comment by OldTyT** [comment]
@Knockback2003, check pls.

**Comment by Knockback2003** [comment]
I think that's fine, I'll test it tomorrow. Thanks for your efforts

**Comment by Knockback2003** [comment]
I think that's fine, I'll test it tomorrow. Thanks for your efforts

**Comment by OldTyT** [comment]
@Knockback2003, does it work?

**Comment by Knockback2003** [comment]
So far, the sublabel has not been included in the Telegram message, although it has been set in Frigate. Maybe the If function doesn't work as intended?

**Comment by OldTyT** [comment]
> So far, the sublabel has not been included in the Telegram message, although it has been set in Frigate. Maybe the If function doesn't work as intended?

Hm...
@Knockback2003, is `sub_label` exactly not `null`?

**Comment by Knockback2003** [comment]
`{
  "before": {
    "id": "1731316026.772492-judaea",
    "camera": "Terasse",
    "frame_time": 1731316034.445506,
    "snapshot": {
      "frame_time": 1731316033.177389,
      "box": [
        160,
        381,
        1001,
        1616
      ],
      "area": 1038635,
      "region": [
        0,
        0,
        3196,
        3196
      ],
      "score": 0.83984375,
      "attributes": []
    },
    "label": "person",
    "sub_label": [
      "nicole",
      null
    ],
    "top_score": 0.8359375,
    "false_positive": false,
    "start_time": 1731316026.772492,
    "end_time": null,
    "score": 0.53515625,
    "box": [
      2,
      1071,
      304,
      1615
    ],
    "area": 164288,
    "ratio": 0.5551470588235294,
    "region": [
      0,
      787,
      872,
      1659
    ],
    "stationary": false,
    "motionless_count": 0,
    "position_changes": 1,
    "current_zones": [],
    "entered_zones": [],
    "has_clip": true,
    "has_snapshot": true,
    "attributes": {},
    "current_attributes": []
  },
  "after": {
    "id": "1731316026.772492-judaea",
    "camera": "Terasse",
    "frame_time": 1731316034.445506,
    "snapshot": {
      "frame_time": 1731316033.177389,
      "box": [
        160,
        381,
        1001,
        1616
      ],
      "area": 1038635,
      "region": [
        0,
        0,
        3196,
        3196
      ],
      "score": 0.83984375,
      "attributes": []
    },
    "label": "person",
    "sub_label": [
      "nicole",
      null
    ],
    "top_score": 0.8359375,
    "false_positive": false,
    "start_time": 1731316026.772492,
    "end_time": 1731316040.392506,
    "score": 0.53515625,
    "box": [
      2,
      1071,
      304,
      1615
    ],
    "area": 164288,
    "ratio": 0.5551470588235294,
    "region": [
      0,
      787,
      872,
      1659
    ],
    "stationary": false,
    "motionless_count": 0,
    "position_changes": 1,
    "current_zones": [],
    "entered_zones": [],
    "has_clip": true,
    "has_snapshot": true,
    "attributes": {},
    "current_attributes": []
  },
  "type": "end"
}`

It seems like the sub_label is a Array Type

**Comment by Knockback2003** [comment]
But I never had 2 sublabels in frigate. If Deepstack detects an other person on the same event it replaces the person's name from the sub_label

**Comment by OldTyT** [comment]
@Knockback2003, check it now, please. Everything works in my console.

**Comment by OldTyT** [comment]
But before that, don't forget to update the image.

**Comment by OldTyT** [comment]
@Knockback2003, check it now, please.

**Comment by Knockback2003** [comment]
Unfortunately it doesn't work for me but it could well be my fault

**Comment by Knockback2003** [comment]
Unfortunately it doesn't work for me but it could well be my fault
