### ISSUE TITLE
Error after recent Update:

### ISSUE THREAD

**Issue by ne0ark** [OldTyT/frigate-telegram#21]
Hello,

I am getting the following error:

```
Error unmarshal json: json: cannot unmarshal string into Go struct field .sub_label of type []interface {}
EventID: ALL
```

Thanks

**Comment by OldTyT** [comment]
Oh...

**Comment by OldTyT** [comment]
@ne0ark, hello!
I am not getting this error. Can you show the data that frigate returns on the endpoint `/api/events` [Docs](https://docs.frigate.video/integrations/api/#get-apievents)?

**Comment by OldTyT** [comment]
This error could have been caused as part of the work on #19

**Comment by OldTyT** [comment]
Was the mistake repeated?

**Comment by levski** [comment]
i just installed and got it running.
about 30mins in i see the same issue.
![image](https://github.com/user-attachments/assets/67200510-abde-4279-a35d-dcf91c436812)

let me know

**Comment by OldTyT** [comment]
@levski, Thank you very much. I fixed it. Please check it out

**Comment by levski** [comment]
> @levski, Thank you very much. I fixed it. Please check it out

it is fixed indeed, my good sir.
much appreciated.

might i ask what it was that fixed it?

**Comment by OldTyT** [comment]
> > @levski, Thank you very much. I fixed it. Please check it out
> 
> it is fixed indeed, my good sir. much appreciated.
> 
> might i ask what it was that fixed it?

https://github.com/OldTyT/frigate-telegram/commit/8ed5f32bda85984c746b59e2913e22454fd4a66c

There was a potential error in the code. I can't check this feature myself, so I disabled it.
