### ISSUE TITLE
Entitiy too large

### ISSUE THREAD

**Issue by RainerZuf** [OldTyT/frigate-telegram#5]
Hi,
first of all, many thanks for providing this repo!
I have the problem that taken videos are sometime too large to send via Telegram and I receive many of those message shown in the screenshot. Is it possible to check first the size of the video (think 40MB is the limit) and if larger then just send the screenshot?

Many thanks!
![tele](https://github.com/OldTyT/frigate-telegram/assets/94378980/3bcbc968-4dc6-49ba-8ecb-b4e0e1216519)

**Comment by OldTyT** [comment]
@RainerZuf, hello!
Thanks for the feedback!
Please tell me, how many cameras do you have simultaneously creating events?

[Limit file size is 50 mb](https://core.telegram.org/bots/faq#how-do-i-upload-a-large-file)

> Is it possible to check first the size of the video (think 40MB is the limit) and if larger then just send the screenshot?

It's a good idea, I'll think about it.

**Comment by RainerZuf** [comment]
Hi,
many thanks for quick response. 
It's currently just one camera at all.

Thanks

**Comment by OldTyT** [comment]
@RainerZuf, please, check this

**Comment by RainerZuf** [comment]
Many thanks for quick solution.
I already updated my stack.
Will come back to you end of next week (9th of Feb) or when problems occur.

Thanks again!

**Comment by RainerZuf** [comment]
Hi, 
tested it for a week now. Works like a charme.

Thanks for quick implementation!

**Comment by OldTyT** [comment]
> Hi, tested it for a week now. Works like a charme.
> 
> Thanks for quick implementation!

Hi!
Very good!
