### ISSUE TITLE
REQUEST: ARM image

### ISSUE THREAD

**Issue by TomTomNavigator** [OldTyT/frigate-telegram#7]
Hey - would love to use this on ARM (raspberry, etc.) - would appreciate if this could be supported! 

`frigate-telegram The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by OldTyT** [comment]
@TomTomNavigator i have added the build and upload of the following docker images:
```
ghcr.io/oldtyt/frigate-telegram:arm32v6
ghcr.io/oldtyt/frigate-telegram:arm32v7
ghcr.io/oldtyt/frigate-telegram:arm64v8
ghcr.io/oldtyt/frigate-telegram:amd64
ghcr.io/oldtyt/frigate-telegram:arm32v6-SHORT_COMMIT_ID
ghcr.io/oldtyt/frigate-telegram:arm32v7-SHORT_COMMIT_ID
ghcr.io/oldtyt/frigate-telegram:arm64v8-SHORT_COMMIT_ID
ghcr.io/oldtyt/frigate-telegram:amd64-SHORT_COMMIT_ID
```
Please see, available tags in [this page](https://github.com/OldTyT/frigate-telegram/pkgs/container/frigate-telegram)
